---
language: node_js
node_js:
- 0.10
before_script:
  - npm install -g grunt-cli
  - git submodule update --init --recursive
env:
  global:
  - secure: ! 'KcV7nN1Rel6aVvYDWHUe2AsSI2mXYP/6ROwZ1uqJzFqLcR/q48ZjNGzO7GG0TVfmHUf+pZLvtVdJVyED0wkJG3hZXrll5QZa59bf4JbY5mmdcbo/H7v6SqI2EGCL2S8EemmhgCyM1oMfz7gztqmRotC2XCp6Or4LnX8aZjM7W2c='
  - secure: ! 'Exv6GS1VsdQLtz/1XieKnn6hknjsEQgl5pa1MnnP73r8CbYZ7/Yh8b5mVRE9ZuflAx1+EEYA9dgvltAKdGTz0HDAp5f0+C28PW5GDZUqRdr4WyiwQN5oHw27nmMSMB3p7iwajHEXVWWF9hpQDaWS2RlPGd7NtOwo5Ve9SemQxIs='
